package com.example.cheerschecklist

enum class AppLanguage {
    ENGLISH,
    POLISH,
}

class Strings(
    val filtersAndSorting: String,
    val category: String,
    val all: String,
    val manageCategories: String,
    val sortBy: String,
    val sortNewest: String,
    val sortName: String,
    val sortRating: String,
    val appTitle: String,
    val filtersButton: String,
    val searchLabel: String,
    val noMatchingEntries: String,
    val noEntriesYet: String,
    val delete: String,
    val cancel: String,
    val deleteEntryTitle: String,
    val deleteEntryText: (String) -> String,
    val editEntryTitle: String,
    val newEntryTitle: String,
    val nameLabel: String,
    val cantBeEmpty: String,
    val brandLabel: String,
    val addYourOwnType: String,
    val add: String,
    val colorLabel: String,
    val oilinessLabel: String,
    val scentLabel: String,
    val flavorLabel: String,
    val ratingLabel: String,
    val dateLabel: (String) -> String,
    val notesLabel: String,
    val save: String,
    val ok: String,
    val discardChangesTitle: String,
    val discardChangesText: String,
    val discard: String,
    val keepEditing: String,
    val manageTypesTitle: String,
    val back: String,
    val noCustomTypesYet: String,
    val rename: String,
    val renameTypeTitle: String,
    val typeNameLabel: String,
    val deleteTypeTitle: String,
    val deleteTypeText: (String) -> String,
    val addPhoto: String,
    val takePhoto: String,
    val chooseFromGallery: String,
    val removePhoto: String,
)

private val EnglishStrings = Strings(
    filtersAndSorting = "Filters & sorting",
    category = "Category",
    all = "ALL",
    manageCategories = "Edit your categories",
    sortBy = "Sort by",
    sortNewest = "Newest",
    sortName = "Name",
    sortRating = "Rating",
    appTitle = "Cheers Checklist",
    filtersButton = "☰ Filters",
    searchLabel = "Search by name or type",
    noMatchingEntries = "No matching entries",
    noEntriesYet = "No entries yet — tap + to add one",
    delete = "Delete",
    cancel = "Cancel",
    deleteEntryTitle = "Delete entry?",
    deleteEntryText = { name -> "Delete \"$name\"? This can't be undone." },
    editEntryTitle = "Edit entry",
    newEntryTitle = "New entry",
    nameLabel = "Name",
    cantBeEmpty = "Can't be empty",
    brandLabel = "Brand (optional)",
    addYourOwnType = "Add your own type",
    add = "Add",
    colorLabel = "Color (optional)",
    oilinessLabel = "Oiliness (optional)",
    scentLabel = "Scent (optional)",
    flavorLabel = "Flavor (optional)",
    ratingLabel = "Rating",
    dateLabel = { date -> "Date: $date" },
    notesLabel = "Notes (optional)",
    save = "Save",
    ok = "OK",
    discardChangesTitle = "Discard changes?",
    discardChangesText = "Are you sure you want to cancel? Your changes won't be saved.",
    discard = "Discard",
    keepEditing = "Keep editing",
    manageTypesTitle = "Manage your types",
    back = "Back",
    noCustomTypesYet = "You haven't added any custom types yet.",
    rename = "Rename",
    renameTypeTitle = "Rename type",
    typeNameLabel = "Type name",
    deleteTypeTitle = "Delete type?",
    deleteTypeText = { name -> "Delete \"$name\"? Entries using this type will be moved to BEER." },
    addPhoto = "Add photo",
    takePhoto = "Take photo",
    chooseFromGallery = "Choose from gallery",
    removePhoto = "Remove",
)

private val PolishStrings = Strings(
    filtersAndSorting = "Filtry i sortowanie",
    category = "Kategoria",
    all = "WSZYSTKIE",
    manageCategories = "Edytuj swoje kategorie",
    sortBy = "Sortuj według",
    sortNewest = "Najnowsze",
    sortName = "Nazwa",
    sortRating = "Ocena",
    appTitle = "Cheers Checklist",
    filtersButton = "☰ Filtry",
    searchLabel = "Szukaj po nazwie lub typie",
    noMatchingEntries = "Brak pasujących wpisów",
    noEntriesYet = "Brak wpisów — dotknij +, aby dodać",
    delete = "Usuń",
    cancel = "Anuluj",
    deleteEntryTitle = "Usunąć wpis?",
    deleteEntryText = { name -> "Usunąć \"$name\"? Tej operacji nie można cofnąć." },
    editEntryTitle = "Edytuj wpis",
    newEntryTitle = "Nowy wpis",
    nameLabel = "Nazwa",
    cantBeEmpty = "Nie może być puste",
    brandLabel = "Marka (opcjonalnie)",
    addYourOwnType = "Dodaj własny typ",
    add = "Dodaj",
    colorLabel = "Kolor (opcjonalnie)",
    oilinessLabel = "Oleistość (opcjonalnie)",
    scentLabel = "Zapach (opcjonalnie)",
    flavorLabel = "Smak (opcjonalnie)",
    ratingLabel = "Ocena",
    dateLabel = { date -> "Data: $date" },
    notesLabel = "Notatki (opcjonalnie)",
    save = "Zapisz",
    ok = "OK",
    discardChangesTitle = "Odrzucić zmiany?",
    discardChangesText = "Czy na pewno chcesz anulować? Twoje zmiany nie zostaną zapisane.",
    discard = "Odrzuć",
    keepEditing = "Kontynuuj edycję",
    manageTypesTitle = "Zarządzaj swoimi typami",
    back = "Wstecz",
    noCustomTypesYet = "Nie dodałeś jeszcze żadnych własnych typów.",
    rename = "Zmień nazwę",
    renameTypeTitle = "Zmień nazwę typu",
    typeNameLabel = "Nazwa typu",
    deleteTypeTitle = "Usunąć typ?",
    deleteTypeText = { name -> "Usunąć \"$name\"? Wpisy z tym typem zostaną przeniesione do BEER." },
    addPhoto = "Dodaj zdjęcie",
    takePhoto = "Zrób zdjęcie",
    chooseFromGallery = "Wybierz z galerii",
    removePhoto = "Usuń",
)

fun stringsFor(language: AppLanguage): Strings = when (language) {
    AppLanguage.ENGLISH -> EnglishStrings
    AppLanguage.POLISH -> PolishStrings
}
